# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'TemperWorks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TemperWorks
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'RxDataSources', '4.0.1'
  pod 'Nuke', '9.1.2'
  pod 'SnapKit', '5.0.1'
  
end
